# Use this file to control the main attributes of the website

# You
name: Taikai Takeda
# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: Taikai Takeda

# SEO description
description: Digital resume for Taikai Takeda, undergraduating student majoing in computer science

# URL of this resume
url: 'http://bigsea.me'

# URL of your personal website (make same as URL if you don't have one)
personal: 'http://bigsea.me'

# these should be pretty self-explanatory :-P
email: 297.1951@gmail.com
twitter: bigsea_t
github: bigsea-t
facebook: taikai.takeda
linkedin: taikaitakeda
#instagram: bigsea____
website: http://bigsea.me

# Show this in the footer
copyright: All rights reserved.

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
analytics: 

# Jekyll assets gem
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets

# Files in this repo that we don't want to go to the web
exclude: [
  'scss',
  '*.rb',
  '*.yml', 
  'vendor', 
  'Gemfile', 
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
]
